openapi: 3.0.1
info:
  title: Beyond Identity API
  description: |
    The Beyond Identity API defines methods for managing realms, directories, credentials, and applications.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: support@beyondidentity.com
  license:
    name: Apache 2.0
    url: 'http://license.com/'
  version: 1.0.0
servers:
  - url: 'https://api-us.beyondidentity.run/v1'
tags:
  - name: Tenants
    description: Tenant methods.
  - name: Realms
    description: Realm methods.
  - name: Groups
    description: Group methods.
  - name: Identities
    description: Identity methods.
  - name: Credentials
    description: Credential methods.
  - name: Credential Binding Jobs
    description: Credential binding job methods.
  - name: Themes
    description: Theme methods.
  - name: Applications
    description: Application methods.
  - name: Authenticator Configs
    description: Authenticator configuration methods.
  - name: Resource Servers
    description: Resource server methods.
paths:
  '/tenants/{tenant_id}':
    get:
      tags:
        - Tenants
      operationId: GetTenant
      summary: Get a tenant.
      description: Gets a tenant.
      security:
        - ManagementAuth:
            - 'tenants:read'
    patch:
      tags:
        - Tenants
      operationId: UpdateTenant
      summary: Update a tenant.
      description: |
        Updates a tenant. Values in the request body for immutable or output-only fields will be ignored. Fields that are omitted from the request body will be left unchanged.
      security:
        - ManagementAuth:
            - 'tenants:update'
    delete:
      tags:
        - Tenants
      operationId: DeleteTenant
      summary: Delete a tenant.
      description: |
        Deletes a tenant. Tenants may only be deleted if they have no realms.
      security:
        - ManagementAuth:
            - 'tenants:delete'
  '/tenants/{tenant_id}/realms':
    post:
      tags:
        - Realms
      operationId: CreateRealm
      summary: Create a realm.
      description: |
        Creates a realm for a tenant. Values in the request body for immutable or output-only fields will be ignored.
      security:
        - ManagementAuth:
            - 'realms:create'
    get:
      tags:
        - Realms
      operationId: ListRealms
      summary: List realms.
      description: |
        Lists realms belonging to a tenant. There is no defined ordering of the
        list of realms in the response.

        When paginating, the page size is maintained by the page token but may be
        overridden on subsequent requests. The skip is not maintained by the page
        token and must be specified on each subsequent request.

        Page tokens expire after one week. Requests which specify an expired page
        token will result in undefined behavior.
      security:
        - ManagementAuth:
            - 'realms:read'
  '/tenants/{tenant_id}/realms/{realm_id}':
    get:
      tags:
        - Realms
      operationId: GetRealm
      summary: Get a realm.
      description: Gets a realm belonging to a tenant.
      security:
        - ManagementAuth:
            - 'realms:read'
    patch:
      tags:
        - Realms
      operationId: UpdateRealm
      summary: Update a realm.
      description: |
        Updates a realm belonging to a tenant. Values in the request body for immutable or output-only fields will be ignored. Fields that are omitted from the request body will be left unchanged.
      security:
        - ManagementAuth:
            - 'realms:update'
    delete:
      tags:
        - Realms
      operationId: DeleteRealm
      summary: Delete a realm.
      description: |
        Deletes a realm belonging to a tenant. Realms may only be deleted if they have no identities or groups.
      security:
        - ManagementAuth:
            - 'realms:delete'
  '/tenants/{tenant_id}/realms/{realm_id}/groups':
    post:
      tags:
        - Groups
      operationId: CreateGroup
      summary: Create a group.
      description: |
        Creates a group within a realm. Values in the request body for immutable or output-only fields will be ignored.
      security:
        - ManagementAuth:
            - 'groups:create'
    get:
      tags:
        - Groups
      operationId: ListGroups
      summary: List groups.
      description: |
        Lists groups within a realm. There is no defined ordering of the list of
        groups in the response.

        When paginating, the page size is maintained by the page token but may be
        overridden on subsequent requests. The skip is not maintained by the page
        token and must be specified on each subsequent request.

        Page tokens expire after one week. Requests which specify an expired page
        token will result in undefined behavior.
      security:
        - ManagementAuth:
            - 'groups:read'
  '/tenants/{tenant_id}/realms/{realm_id}/groups/{group_id}':
    get:
      tags:
        - Groups
      operationId: GetGroup
      summary: Get a group.
      description: Gets a group within a realm.
      security:
        - ManagementAuth:
            - 'groups:read'
    patch:
      tags:
        - Groups
      operationId: UpdateGroup
      summary: Update a group.
      description: |
        Updates a group within a realm. Values in the request body for immutable or output-only fields will be ignored. Fields that are omitted from the request body will be left unchanged.
      security:
        - ManagementAuth:
            - 'groups:update'
    delete:
      tags:
        - Groups
      operationId: DeleteGroup
      summary: Delete a group.
      description: |
        Deletes a group within a realm. Groups may only be deleted if they have no members.
      security:
        - ManagementAuth:
            - 'groups:delete'
  '/tenants/{tenant_id}/realms/{realm_id}/groups/{group_id}:listMembers':
    get:
      tags:
        - Groups
      operationId: ListGroupMembers
      summary: List group members.
      description: Lists the identities that belong to a group.
      security:
        - ManagementAuth:
            - 'groups:read'
            - 'identities:read'
  '/tenants/{tenant_id}/realms/{realm_id}/groups/{group_id}:addMembers':
    post:
      tags:
        - Groups
      operationId: AddGroupMembers
      summary: Add members to a group.
      description: Adds members to a group.
      security:
        - ManagementAuth:
            - 'groups:update'
            - 'identities:read'
  '/tenants/{tenant_id}/realms/{realm_id}/groups/{group_id}:deleteMembers':
    post:
      tags:
        - Groups
      operationId: DeleteGroupMembers
      summary: Deletes members from a group.
      description: Deletes members from a group.
      security:
        - ManagementAuth:
            - 'groups:update'
            - 'identities:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities':
    post:
      tags:
        - Identities
      operationId: CreateIdentity
      summary: Create an identity.
      description: |
        Creates an identity within a realm. Values in the request body for immutable or output-only fields will be ignored.
      security:
        - ManagementAuth:
            - 'identities:create'
    get:
      tags:
        - Identities
      operationId: ListIdentities
      summary: List identities.
      description: |
        Lists identities within a realm. There is no defined ordering of the
        list of identities in the response.

        When paginating, the page size is maintained by the page token but may be
        overridden on subsequent requests. The skip is not maintained by the page
        token and must be specified on each subsequent request.

        Page tokens expire after one week. Requests which specify an expired page
        token will result in undefined behavior.
      security:
        - ManagementAuth:
            - 'identities:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id}':
    get:
      tags:
        - Identities
      operationId: GetIdentity
      summary: Get an identity.
      description: Gets an identity within a realm.
      security:
        - ManagementAuth:
            - 'identities:read'
    patch:
      tags:
        - Identities
      operationId: UpdateIdentity
      summary: Update an identity.
      description: |
        Updates an identity within a realm. Values in the request body for immutable or output-only fields will be ignored. Fields that are omitted from the request body will be left unchanged.
      security:
        - ManagementAuth:
            - 'identities:update'
    delete:
      tags:
        - Identities
      operationId: DeleteIdentity
      summary: Delete an identity.
      description: |
        Deletes an identity within a realm. Identities may only be deleted if they have no credentials.
      security:
        - ManagementAuth:
            - 'identities:delete'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id}:listGroups':
    get:
      tags:
        - Identities
      operationId: ListIdentityGroups
      summary: List an identity's groups.
      description: List the groups to which an identity belongs.
      security:
        - ManagementAuth:
            - 'identities:read'
            - 'groups:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id}/credentials/{credential_id}':
    get:
      tags:
        - Credentials
      operationId: GetCredential
      summary: Get a credential.
      description: Gets a credential.
      security:
        - ManagementAuth:
            - 'credentials:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id}/credentials/{credential_id}:revoke':
    post:
      tags:
        - Credentials
      operationId: RevokeCredential
      summary: Revoke a credential.
      description: Revokes a credential
      security:
        - ManagementAuth:
            - 'credentials:revoke'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id_or_wildcard}/credentials':
    get:
      tags:
        - Credentials
      operationId: ListCredentials
      summary: List credentials.
      description: |
        Lists credentials.
        Supports filtering (using the `filter` request parameter) by the following attributes: `state`, `jwk_thumbprint`. See the Credential resource schema for details about those attributes.
      security:
        - ManagementAuth:
            - 'credentials:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id_or_wildcard}/credential-binding-jobs':
    get:
      tags:
        - Credential Binding Jobs
      operationId: ListCredentialBindingJobs
      summary: List credential binding jobs.
      description: Lists credential binding jobs.
      security:
        - ManagementAuth:
            - 'credential-binding-jobs:read'
  '/tenants/{tenant_id}/realms/{realm_id}/identities/{identity_id}/credential-binding-jobs/{credential_binding_job_id}':
    get:
      tags:
        - Credential Binding Jobs
      operationId: GetCredentialBindingJob
      summary: Get a credential binding job.
      description: Gets a credential binding job.
      security:
        - ManagementAuth:
            - 'credential-binding-jobs:read'
  '/tenants/{tenant_id}/realms/{realm_id}/themes':
    post:
      tags:
        - Themes
      description: |
        Create a theme for a realm. All are optional and will be populated with  defaults if not provided.
      operationId: CreateTheme
      security:
        - ManagementAuth:
            - 'themes:create'
  '/tenants/{tenant_id}/realms/{realm_id}/themes/active':
    get:
      tags:
        - Themes
      description: |
        Get the active theme for a realm. If the realm has not specified an active theme a default theme will be returned. In that case, the returned theme will not have the id field populated.
      operationId: GetActiveTheme
      security:
        - ManagementAuth:
            - 'themes:read'
  '/tenants/{tenant_id}/realms/{realm_id}/themes/{theme_id}':
    get:
      tags:
        - Themes
      description: Get a theme.
      operationId: GetTheme
      security:
        - ManagementAuth:
            - 'themes:read'
    patch:
      tags:
        - Themes
      description: Update a theme.
      operationId: UpdateTheme
      security:
        - ManagementAuth:
            - 'themes:update'
  '/tenants/{tenant_id}/realms/{realm_id}/applications':
    get:
      operationId: ListApplications
      tags:
        - Applications
      summary: Lists Applications by Realm.
      description: Lists Applications by Realm.
    post:
      operationId: CreateApplication
      tags:
        - Applications
      summary: Creates a new Application.
      description: Creates a new Application.
  '/tenants/{tenant_id}/realms/{realm_id}/applications/{application_id}':
    get:
      operationId: GetApplication
      tags:
        - Applications
      summary: Finds an Application by its ID.
      description: Finds an Application by its ID.
    patch:
      operationId: UpdateApplication
      tags:
        - Applications
      summary: Updates an Application by its ID.
      description: Updates an Application by its ID.
    delete:
      operationId: DeleteApplication
      tags:
        - Applications
      summary: Deletes an Application by its ID.
      description: Deletes an Application by its ID.
  '/tenants/{tenant_id}/realms/{realm_id}/authenticator-configs':
    get:
      operationId: ListAuthenticatorConfig
      tags:
        - Authenticator Configs
      summary: Lists Authenticator Configs by Realm.
      description: Lists Authenticator Configs by Realm.
    post:
      operationId: CreateAuthenticatorConfig
      tags:
        - Authenticator Configs
      summary: Creates a new Authenticator Config.
      description: Creates a new Authenticator Config.
  '/tenants/{tenant_id}/realms/{realm_id}/authenticator-configs/{authenticator_config_id}':
    get:
      operationId: GetAuthenticatorConfig
      tags:
        - Authenticator Configs
      summary: Finds an Authenticator Config by its ID.
      description: Finds an Authenticator Config by its ID.
    patch:
      operationId: UpdateAuthenticatorConfig
      tags:
        - Authenticator Configs
      summary: Updates an Authenticator Config by its ID.
      description: Updates an Authenticator Config by its ID.
    delete:
      operationId: DeleteAuthenticatorConfig
      tags:
        - Authenticator Configs
      summary: Deletes an Authenticator Config by its ID.
      description: Deletes an Authenticator Config by its ID.
  '/tenants/{tenant_id}/realms/{realm_id}/resource-servers':
    get:
      summary: Lists resource servers by realm.
      description: Lists resource servers by realm.
      tags:
        - Resource Servers
      operationId: ListResourceServers
    post:
      summary: Creates a new Resource Server.
      description: Creates a new Resource Server.
      tags:
        - Resource Servers
      operationId: CreateResourceServer
  '/tenants/{tenant_id}/realms/{realm_id}/resource-servers/{resource_server_id}':
    get:
      summary: Finds a Resource Server by its ID.
      description: Finds a Resource Server by its ID.
      tags:
        - Resource Servers
      operationId: GetResourceServer
    delete:
      summary: Deletes a Resource Server by its ID.
      description: Deletes a Resource Server by its ID.
      tags:
        - Resource Servers
      operationId: DeleteResourceServer
    patch:
      summary: Updates a Resource Server by its ID.
      description: Updates a Resource Server by its ID.
      tags:
        - Resource Servers
      operationId: update_rs
components:
  securitySchemes:
    ManagementAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - ManagementAuth: []
