/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generating sidebar manually rather than `autogenerated` because can't 
  // find a way to add links to the sidebar with autogeneration. 
  mySidebar: [
    'index',
    'send-enrollment',
    'bubble-io-integration',
    'expo-react-native',
    'integrate-nextauth',
    'integrate-wordpress',
    {
      type: 'category',
      label: 'SSO Integrations',
      collapsed: true,
      items: [{
        type: 'autogenerated',
        dirName: 'sso-integrations',
      }],
    },
  ],
};

module.exports = sidebars;
