name: 📕 Content Issue
description: Report missing or inaccurate content on the docs
labels: ["triage"]
title: "[Content issue]: "
body:
  - type: input
    attributes:
      label: URL
      description: The URL at which the content is missing or inaccurate
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Please provide a clear and concise description of the bug or issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please provide screenshots depicting the problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.

